// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAEHr1cOR4ThniP70vXTkgTcd2PS_mWuE',
    appId: '1:1005142457785:web:1e61b81d2f68031d2f0a68',
    messagingSenderId: '1005142457785',
    projectId: 'flutterchess-c9414',
    authDomain: 'flutterchess-c9414.firebaseapp.com',
    storageBucket: 'flutterchess-c9414.appspot.com',
    measurementId: 'G-2BMSRBTE17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ta5tDmJBN5WkMVBCRDXwu3vqL7uK73Y',
    appId: '1:1005142457785:android:350a7e6da96fc0502f0a68',
    messagingSenderId: '1005142457785',
    projectId: 'flutterchess-c9414',
    storageBucket: 'flutterchess-c9414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAROrb2bENS4IQXpUF_RkbduLTabArH24E',
    appId: '1:1005142457785:ios:b938db8f1984a9ad2f0a68',
    messagingSenderId: '1005142457785',
    projectId: 'flutterchess-c9414',
    storageBucket: 'flutterchess-c9414.appspot.com',
    iosBundleId: 'com.example.chess',
  );
}
